[package]
name = "reaper"
version = "0.1.0"
edition = "2021"
authors = ["Miguel"]
description = "A Rust project"
repository = "https://github.com/miguelgi/reaper"
license = "MIT"

[dependencies]

[dev-dependencies]

[[bin]]
name = "reaper"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.test]
opt-level = 2
